//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMHO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RESOURCE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RESOURCE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMHO.RESOURCE", typeof(RESOURCE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de Medicina.
        /// </summary>
        public static string CantidadMedicina {
            get {
                return ResourceManager.GetString("CantidadMedicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direcci&amp;oacute;n.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de Usuario.
        /// </summary>
        public static string EstadoUsuario {
            get {
                return ResourceManager.GetString("EstadoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Caducidad.
        /// </summary>
        public static string FechaCaducidad {
            get {
                return ResourceManager.GetString("FechaCaducidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contrase&amp;tilde;a debe coincidir.
        /// </summary>
        public static string FormErr {
            get {
                return ResourceManager.GetString("FormErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Campo es Requerido.
        /// </summary>
        public static string FormErrCampoRequerido {
            get {
                return ResourceManager.GetString("FormErrCampoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingresar caracteres validos.
        /// </summary>
        public static string FormErrRegEx {
            get {
                return ResourceManager.GetString("FormErrRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidad.
        /// </summary>
        public static string IdEspecialidad {
            get {
                return ResourceManager.GetString("IdEspecialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Medicina.
        /// </summary>
        public static string IdEstadoMedicina {
            get {
                return ResourceManager.GetString("IdEstadoMedicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado del Usuario.
        /// </summary>
        public static string IdEstadoUsuario {
            get {
                return ResourceManager.GetString("IdEstadoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario de Trabajo.
        /// </summary>
        public static string IdHorarioTrabajo {
            get {
                return ResourceManager.GetString("IdHorarioTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa&amp;iacute;s de Nacimiento.
        /// </summary>
        public static string IdPaisNacimiento {
            get {
                return ResourceManager.GetString("IdPaisNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la medicina.
        /// </summary>
        public static string NombreMedicina {
            get {
                return ResourceManager.GetString("NombreMedicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha registrado un nuevo paciente.
        /// </summary>
        public static string PacienteNuevoRegistrado {
            get {
                return ResourceManager.GetString("PacienteNuevoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de la Medicina.
        /// </summary>
        public static string PrecioMedicina {
            get {
                return ResourceManager.GetString("PrecioMedicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer Apellido.
        /// </summary>
        public static string PrimerApellido {
            get {
                return ResourceManager.GetString("PrimerApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer Nombre.
        /// </summary>
        public static string PrimerNombre {
            get {
                return ResourceManager.GetString("PrimerNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol del Usuario.
        /// </summary>
        public static string RolUsuario {
            get {
                return ResourceManager.GetString("RolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Apellido.
        /// </summary>
        public static string SegundoApellido {
            get {
                return ResourceManager.GetString("SegundoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Nombre.
        /// </summary>
        public static string SegundoNombre {
            get {
                return ResourceManager.GetString("SegundoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona al menos un día.
        /// </summary>
        public static string SeleccionaDia {
            get {
                return ResourceManager.GetString("SeleccionaDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona Estado.
        /// </summary>
        public static string SeleccionarEstado {
            get {
                return ResourceManager.GetString("SeleccionarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el Rol.
        /// </summary>
        public static string SeleccionaRol {
            get {
                return ResourceManager.GetString("SeleccionaRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Pais.
        /// </summary>
        public static string SeleccionarPais {
            get {
                return ResourceManager.GetString("SeleccionarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Sexo {
            get {
                return ResourceManager.GetString("Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Identificaci&amp;oacute;n debe ser &amp;uacute;nica.
        /// </summary>
        public static string UniqueId {
            get {
                return ResourceManager.GetString("UniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO.
        /// </summary>
        public static string USUARIO {
            get {
                return ResourceManager.GetString("USUARIO", resourceCulture);
            }
        }
    }
}
